name: SortuniqScript

on: [push]

jobs:
  RunShFile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: List
      run: ls -alh

    - name: ChangeFileMode
      run: chmod +x sort.sh
      
    - name: List
      run: ls -alh

    - name: RunShFile
      run: ./sort.sh fruits.txt